baseurl = "https://seisscoped.github.io/"
languageCode = "en-us"
title = "SCOPED"
theme = "ananke"

paginate = 3

summaryLength = 30
enableEmoji = true
pygmentsCodeFences = true

enableRobotsTXT = true

[author]
    name = "SCOPED Team"
    github = "https://github.com/SeisSCOPED"
    facebook = "https://business.facebook.com/SeisScoped/"
    twitter = "https://twitter.com/SEIS_SCOPED"

[[menu.main]]
    name = "Home" 
    weight = 10 
    url = "/" 
[[menu.main]]
    name = "News" 
    weight = 20 
    url = "/news/" 
[[menu.main]]
    name = "About"
    weight = 30
    url = "/about/"

# -------------
# Customization
# -------------
[params]
  coverImage = "images/cover.jpg"

  imageGallery = true

  thumbnailImage = true
  thumbnailImagePosition = "bottom"
  autoThumbnailImage = true
