baseURL = "https://seisscoped.github.io/"
languageCode = "en-us"
title = "SCOPED"
theme = "tranquilpeak"

enableRobotsTXT = true

[[menu.main]]
    name = "Home" 
    weight = 1 
    url = "/" 
[[menu.main]]
    name = "About"
    weight = 2
    url = "/about/"
[[menu.main]]
    name = "People"
    weight = 3
    url = "/people/"
[[menu.main]]
    name = "News"
    weight = 4
    url = "/news/"
