baseURL = "https://seisscoped.github.io/"
languageCode = "en-us"
title = "SCOPED"
theme = "tranquilpeak"

enableRobotsTXT = true

[[menu.main]]
    name = "Home" 
    weight = 1 
    url = "/" 
[[menu.main]]
    name = "About"
    weight = 2
    url = "/about/"

# -------------
# Customization
# -------------
[params]
  coverImage = "images/cover.jpg"

  imageGallery = true

  thumbnailImage = true
  thumbnailImagePosition = "bottom"
  autoThumbnailImage = true
